baseURL = "https://hsterts.github.io/h-docs/"
languageCode = "en-us"
googleAnalytics = "G-2KM7MBX5DR"
relativeURLs = false
disablePathToLower = true
ignoreFiles = [
    "/content/templates/*",
    "/content/private/*",
    "/content/sfinder-docs/sfinder spin.md"
]
summaryLength = 20
paginate = 10
enableGitInfo = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        lastmod = ["lastmod", ":git", "date", "publishDate"]
        publishDate = ["publishDate", "date"]
    [markup.goldmark.renderer]
        unsafe = true